config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => '/res' if Rails.env.development?
  devise_for :users

  get "submit_request_to_join", to: "submit_request_to_join#new"
  post "submit_request_to_join", to: "submit_request_to_join#create"

  post "set_price_per_word", to: "set_price_per_word#create"

  resource :dashboard, only: %i[show]
  namespace :requesters do
    resource :dashboard, only: %i[show]
  end
  namespace :esperantists do
    resource :dashboard, only: %i[show]
  end
  namespace :translators do
    resource :dashboard, only: %i[show]
  end
  namespace :admins do
    resource :dashboard, only: %i[show]
    resources :requests_to_join, only: %i[index show]
  end

  resources :translation_requests, only: %i[new create show] do
    resource :billing_address, only: %i[new create], module: :translation_requests
    resource :payments, only: %i[new create], module: :translation_requests
    namespace :stripe do
      resource :complete, only: %i[show]
    end
    resource :accepted, only: %i[show], module: :translation_requests
  end

  root "home#index"
end

app/controllers/translation_requests/accepteds_controller.rb
module TranslationRequests
  class AcceptedsController < ApplicationController
    layout "dashboard"
    before_action :authenticate_user!

    def show
      @translation_request = TranslationRequests::TranslationRequest.find(params[:translation_request_id])
    end
  end
end

app/controllers/translation_requests/billing_addresses_controller.rb
module TranslationRequests
  class BillingAddressesController < ApplicationController
    layout "dashboard"
    before_action :authenticate_user!

    def new
      @translation_request = TranslationRequests::TranslationRequest.find(params[:translation_request_id])
      @translation_requester = TranslationRequesters::TranslationRequester.find(current_user.uuid)
    end

    def create
      @form = SetBillingAddressForm.new(
        line1: params[:line1],
        line2: params[:line2],
        city: params[:city],
        postal_code: params[:postal_code],
        state: params[:state],
        country: params[:country]
      )
      render_errors and return unless @form.valid?

      @translation_request = TranslationRequests::TranslationRequest.find(params[:translation_request_id])
      command_bus.(
        Billing::SetBillingAddressOfTranslationRequest.new(
          translation_request_id: @translation_request.id,
          line1: @form.line1,
          line2: @form.line2,
          city: @form.city,
          postal_code: @form.postal_code,
          state: @form.state,
          country: @form.country,
          set_as_default: false
        )
      )

      redirect_to translation_request_path(@translation_request.id)
    end

    private

    def render_errors
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/translation_requests/payments_controller.rb
module TranslationRequests
  class PaymentsController < ApplicationController
    layout "dashboard"
    before_action :authenticate_user!

    def new
      @translation_request = TranslationRequests::TranslationRequest.find(params[:translation_request_id])
      @translation_requester = TranslationRequesters::TranslationRequester.find(current_user.uuid)
    end

    def create
      @translation_request = TranslationRequests::TranslationRequest.find(params[:translation_request_id])
      payment_id = SecureRandom.uuid

      command_bus.(
        Payments::SubmitPaymentWithStripe.new(
          payment_id: payment_id,
          translation_request_id: @translation_request.id,
          payment_method_id: params[:payment_method_id],
          amount: @translation_request.total,
          customer_ip: request.ip,
          customer_user_agent: request.user_agent
        )
      )

      render json: { redirectUrl: translation_request_path(@translation_request) }
    end

    private

    def render_errors
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/translation_requests_controller.rb
class TranslationRequestsController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!

  def new
    @form = RequestTranslationForm.new({source_languague: "", target_languague: "", translation_text: ""})
  end

  def show
    @translation_request = TranslationRequests::TranslationRequest.find(params[:id])

    redirect_to_new_billing_address_path and return if @translation_request.status == "amount_calculated"
    redirect_to_new_payment_path and return if @translation_request.status == "total_calculated"
    redirect_to_accepted_translation_request_path and return if @translation_request.status == "accepted"
  end

  def create
    @form = RequestTranslationForm.new(
      source_languague: params[:source_languague],
      target_languague: params[:target_languague],
      translation_text: params[:translation_text]
    )
    render_errors and return unless @form.valid?

    translation_request_id = SecureRandom.uuid
    translation_requester_id = current_user.uuid
    command_bus.(
      Requesting::SubmitTranslationRequest.new(
        translation_request_id: translation_request_id,
        translation_requester_id: translation_requester_id,
        source_languague: @form.source_languague,
        target_languague: @form.target_languague,
        translation_text: {
          raw: @form.translation_text,
          word_count: nil
        }
      )
    )

    redirect_to translation_request_path(translation_request_id), status: :see_other
  rescue Requesting::TranslationRequest::MaxNumberOfWordsExceeded
    flash[:notice] = "Max number of words exceeded"
    render :new, status: :unprocessable_entity
  end

  private

  def redirect_to_new_billing_address_path
    redirect_to new_translation_request_billing_address_path(@translation_request.id)
  end

  def redirect_to_new_payment_path
    redirect_to new_translation_request_payments_path(@translation_request.id)
  end

  def redirect_to_accepted_translation_request_path
    redirect_to translation_request_accepted_path(@translation_request.id)
  end

  def render_errors
    render :new, status: :unprocessable_entity
  end
end

app/views/translation_requests/new.html.erb
<div class="flex justify-center">
  <%= form_with url: translation_requests_path, method: :post, html: { class: "w-full md:w-1/2 bg-gray-200 bg-white shadow-sm ring-1 ring-gray-900/5 sm:rounded-xl md:col-span-2" } do |form| %>
    <%= render "shared/form_errors", form: @form %>
    <div class="px-4 py-6 sm:p-8">
      <div class="grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        <div class="sm:col-span-3">
          <label for="first-name" class="block text-sm font-medium leading-6 text-gray-900">From (source languague)</label>
          <div class="mt-2">
            <%= form.select(:source_languague, [["Spanish", "es"], ["English", "en"]], {:include_blank => "Select", selected: @form.source_languague}, {:class => "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"} ) %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <label for="last-name" class="block text-sm font-medium leading-6 text-gray-900">To (target languague)</label>
          <div class="mt-2">
            <%= form.select(:target_languague, [["Spanish", "es"], ["English", "en"]], {:include_blank => "Select", selected: @form.target_languague}, {:class => "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"} ) %>
          </div>
        </div>
      </div>

      <div class="mt-4">
        <label for="comment" class="block text-sm font-medium leading-6 text-gray-900">What would you like to translate?</label>
        <div class="mt-2">
          <%= form.text_area :translation_text, value: @form.translation_text, rows: 4, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>
    </div>
    <div class="flex items-center justify-end gap-x-6 border-t border-gray-900/10 px-4 py-4 sm:px-8">
      <button type="button" class="text-sm font-semibold leading-6 text-gray-900">Cancel</button>
      <%= form.submit "Submit", class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  <% end %>
</div>