config/routes.rb
Rails.application.routes.draw do
  mount RailsEventStore::Browser => '/res' if Rails.env.development?
  devise_for :users

  get "submit_request_to_join", to: "submit_request_to_join#new"
  post "submit_request_to_join", to: "submit_request_to_join#create"

  post "set_price_per_word", to: "set_price_per_word#create"

  resource :dashboard, only: %i[show]
  namespace :requesters do
    resource :dashboard, only: %i[show]
  end
  namespace :esperantists do
    resource :dashboard, only: %i[show]
  end
  namespace :translators do
    resource :dashboard, only: %i[show]
  end
  namespace :admins do
    resource :dashboard, only: %i[show]
    resources :requests_to_join, only: %i[index show]
  end

  resources :translation_requests, only: %i[new create show] do
    resource :billing_address, only: %i[new create], module: :translation_requests
    resource :payments, only: %i[new create], module: :translation_requests
    namespace :stripe do
      resource :complete, only: %i[show]
    end
    resource :accepted, only: %i[show], module: :translation_requests
  end

  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<!-- Hero -->
<div class="relative overflow-hidden before:absolute before:top-0 before:start-1/2 before:bg-[url('https://preline.co/assets/svg/examples/squared-bg-element.svg')] dark:before:bg-[url('https://preline.co/assets/svg/examples-dark/squared-bg-element.svg')] before:bg-no-repeat before:bg-top before:size-full before:-z-[1] before:transform before:-translate-x-1/2">
  <div class="max-w-[85rem] mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-10">
    <!-- Title -->
    <div class="mt-5 max-w-xl text-center mx-auto">
      <h1 class="block font-bold text-gray-800 text-4xl md:text-5xl lg:text-6xl dark:text-neutral-200">
        Tradukreto pere de Esperanto
      </h1>
    </div>
    <!-- End Title -->

    <div class="mt-5 max-w-3xl text-center mx-auto">
      <p class="text-lg text-gray-600 dark:text-neutral-400">Tradukanto A tradukas de sia denaska lingvo al Esperanto kaj Tradukanto B tradukas de Esperanto al sia denaska lingvo.</p>
    </div>

    <!-- Buttons -->
    <div class="mt-8 gap-3 flex justify-center">
      <a class="py-2 px-3 inline-flex items-center gap-x-2 text-sm font-medium rounded-xl border border-transparent bg-lime-400 text-black hover:bg-lime-500 transition disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:bg-lime-500" href="<%= submit_request_to_join_path %>">
        Aliĝi
        <svg class="flex-shrink-0 size-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>
      </a>
    </div>
    <!-- End Buttons -->
  </div>
</div>
<!-- End Hero -->